// react-railz-connect/src/App.jsx
import './App.css';
import RailzConnect from '@railzai/railz-connect';
import React, {useEffect, useRef} from "react";

const widget = new RailzConnect();

function App() {
  const ref = useRef();

  useEffect(() => {
    widget.mount({
      parentElement: ref.current,
      widgetId: '<Your Widget Id>',
    });
  },[])
  
  return (
    <div className="App">
      <header className="App-header">
        <p>Welcome</p>
        <p>This is a sample Railz Connect project using React</p>
        <p>
          Edit <code>src/App.jsx</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://docs.railz.ai/docs/railz-connect-overview"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn Railz Connect
        </a>
      </header>
      <div>
        <div id='railz-connect' ref={ref}/>
      </div>
    </div>
  );
}

export default App;

// angular/src/app/app.component.ts
import { AfterViewInit, Component, ElementRef, ViewChild } from '@angular/core';

import RailzConnect from '@railzai/railz-connect';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements AfterViewInit {
  @ViewChild('railzConnect', { static: false }) railzConnect: ElementRef;

  ngAfterViewInit(): void {
    const widget = new RailzConnect();
    widget.mount({
      parentElement: this.railzConnect.nativeElement,
      widgetId: '<Your Widget Id>'
    });
  }
}

<!-- Toolbar -->
<div class="content" role="main">
  <div class="toolbar" role="banner">
    <h1>Welcome</h1>
    <p>This is a sample Railz Connect project using Angular</p>
    <p>
      Edit <code>src/app/app.component.ts</code> to pass it your required parameters and save to reload.
    </p>
    <a
      href="https://docs.railz.ai/docs/railz-connect-overview"
      target="_blank"
      rel="noopener noreferrer"
    >
      Learn Railz Connect
    </a>
  </div>

    <div id='railz-connect' #railzConnect></div>
</div>
